# Generated by Django 4.2.13 on 2025-08-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_to', models.TextField()),
                ('order_id', models.CharField(max_length=255)),
                ('asin', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('customizations', models.TextField()),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
