# Generated by Django 4.2.13 on 2025-08-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_shippinglabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinglabel',
            name='customizations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shippinglabel',
            name='ship_to',
            field=models.TextField(blank=True, default=''),
        ),
    ]
