# Generated by Django 4.2.13 on 2025-08-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_alter_shippinglabel_customizations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinglabel',
            name='sku',
        ),
        migrations.AddField(
            model_name='shippinglabel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_labels', to='masterdata.product'),
            preserve_default=False,
        ),
    ]
