# Generated by Django 4.2.13 on 2025-08-31 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_rename_shippinglabel_packingslip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingslip',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_slips', to='masterdata.product'),
        ),
    ]
