# Generated by Django 4.2.13 on 2025-08-31 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_alter_packingslip_product'),
        ('masterdata', '0007_packingslip_folder_path'),
    ]

    operations = [
    ]
