# Generated by Django 4.2.13 on 2025-08-31 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_merge_20250901_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('packing_slip', 'Packing Slip'), ('shipping_label', 'Shipping Label')], max_length=20)),
                ('file_path', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packing_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='masterdata.packingslip')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
