# Generated by Django 4.2.13 on 2025-08-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0009_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
