# Generated by Django 4.2.13 on 2025-09-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0011_packingslip_item_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('packing_slip', 'Packing Slip'), ('shipping_label', 'Shipping Label'), ('dst', 'DST File'), ('dgt', 'DGT File')], max_length=20),
        ),
    ]
