# Generated by Django 4.2.13 on 2025-09-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0012_alter_file_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingslip',
            name='status',
            field=models.CharField(choices=[('new_order', 'New Order'), ('digitizing', 'Digitizing'), ('ready_for_production', 'Ready For Production'), ('in_production', 'In Production'), ('quality_check', 'Quality Check'), ('ready_to_ship', 'Ready to Ship'), ('shipped', 'Shipped')], default='new_order', max_length=30),
        ),
    ]
