# Generated by Django 4.2.13 on 2025-09-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_packingslip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingslip',
            name='tracking_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='packingslip',
            name='tracking_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='packingslip',
            name='tracking_vendor',
            field=models.CharField(blank=True, choices=[('fedex', 'FedEx'), ('ups', 'UPS'), ('usps', 'USPS')], default='', max_length=10),
        ),
    ]
