# Generated by Django 4.2.13 on 2025-09-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0014_packingslip_tracking_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packingslip',
            name='tracking_link',
        ),
    ]
