# Generated by Django 4.2.13 on 2025-12-01 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0015_remove_packingslip_tracking_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('shipping', 'Shipping'), ('materials', 'Materials'), ('labor', 'Labor'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('marketing', 'Marketing'), ('software', 'Software'), ('supplies', 'Supplies'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='masterdata.account')),
            ],
            options={
                'ordering': ('-date', '-created_at'),
            },
        ),
    ]
