# Generated by Django 5.2.6 on 2025-12-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0016_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingslip',
            name='status',
            field=models.CharField(choices=[('new_order', 'New Order'), ('digitizing', 'Digitizing'), ('ready_for_production', 'Ready For Production'), ('in_production', 'In Production'), ('quality_check', 'Quality Check'), ('ready_to_ship', 'Ready to Ship'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='new_order', max_length=30),
        ),
    ]
