# Generated by Django 4.2.13 on 2025-07-25 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('service_account_json', models.FileField(upload_to='service_accounts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdrive_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Drive Setting',
                'verbose_name_plural': 'Google Drive Settings',
                'ordering': ('-created_at',),
            },
        ),
    ]
