# Generated by Django 4.2.13 on 2025-09-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_googledrivesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivesettings',
            name='root_folder_name',
            field=models.CharField(default='EMB', help_text='Name of the root folder within the shared drive', max_length=255),
        ),
        migrations.AddField(
            model_name='googledrivesettings',
            name='shared_drive_name',
            field=models.CharField(default='EMB Test', help_text='Name of the shared Google Drive', max_length=255),
        ),
    ]
