# Generated by Django 4.2.13 on 2025-11-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_googledrivesettings_root_folder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivesettings',
            name='track123_api_key',
            field=models.CharField(blank=True, default='', help_text='Track123 API key for package tracking', max_length=255),
        ),
    ]
